[project]
name = "shanghai-dialect-digitizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.0",
    "pillow-jxl-plugin>=1.3.7",
    "pymupdf>=1.26.7",
]
